site_name: Query Commander Docs
site_url: https://querycommander.com/
repo_url: https://github.com/lnxusr1/query-commander/

theme: 
    name: readthedocs
    highlightjs: true
    prev_next_buttons_location: none
    titles_only: true
    collapse_navigation: false
    logo: https://docs.querycommander.com/en/latest/images/logo-white.png
    favicon: https://docs.querycommander.com/en/latest/images/favicon.svg

nav:
    - Overview: 'index.md'
    - About: 'about.md'
    - Installation: 
      - 'Apache 2.x (httpd)': 'installation/apache.md'
      - 'AWS (Lambda)': 'installation/aws.md'
    - Configuration:
      - Connections: 'configuration/connections.md'
      - Authentication: 'configuration/authenticator.md'
      - 'Session Management': 'configuration/tokenizer.md'
      - Options: 'configuration/options.md'

    - Links:
      - '@ Report Bugs & Issues': 'https://github.com/lnxusr1/query-commander/issues'
      - '@ Code': 'https://github.com/lnxusr1/query-commander/'
      #- '@ Community': 'https://github.com/lnxusr1/query-commander/discussion'
      #- '@ Website': 'https://querycommander.com'

plugins:
  - search

markdown_extensions:
  - admonition