settings:
  log_level: debug
  records_per_request: 200

tokenizer:
  type: local
  timeout: 20 # minutes
  safe_password: abc123456abcdef
  path: /tmp/tokens

authenticator:
  type: local

connections:
  type: config
  items:
    - name: myconn1
      type: postgres
      host: localhost
      port: 5432

    - name: myconn2
      type: mysql
      host: localhost
      port: 3306

    - name: myconn3
      type: oracle
      host: my-oracle-server.lan
      port: 1521
      service_name: freepdb1