settings:
  records_per_request: 200

tokenizer:
  type: local
  timeout: 20 # minutes
  path: /tmp/tokens
  safe_password: abc123456abcdef

authenticator:
  type: local

connections:
  - name: myconn1
    type: postgres
    host: my-db-server.lan
    port: 5432

  - name: myconn2
    type: postgres
    host: localhost
    port: 5432
